[workspace.package]
authors = [
  "Julien Peeters <julien.peeters@mountainhacks.fr"
]
edition = "2021"
version = "0.1.0"

[workspace]
members = [
  "app",
  "cmd",
  "domain",
  "ifconfig",
]

default-members = [ "cmd" ]
