[package]
name = "app"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
domain = { path = "../domain" }
reqwest = { version = "0.11.17", features = ["json"] }
